// Static list of all 132 Army Public Schools (APS) in India.
// This site is dedicated to APS students — schools are fixed and known,
// so there's no 'request new school' / admin-approval flow needed anymore.
// Selecting a school just gets-or-creates its Firestore doc idempotently.

export const APS_SCHOOLS = [
  { id: "aps-agartala", name: "APS Agartala" },
  { id: "aps-agra", name: "APS Agra" },
  { id: "aps-ahmedabad", name: "APS Ahmedabad" },
  { id: "aps-ahmednagar", name: "APS Ahmednagar" },
  { id: "aps-akhnoor", name: "APS Akhnoor" },
  { id: "aps-almora", name: "APS Almora" },
  { id: "aps-alwar", name: "APS Alwar" },
  { id: "aps-ambala", name: "APS Ambala" },
  { id: "aps-amritsar", name: "APS Amritsar" },
  { id: "aps-asc-centre-college-bengaluru", name: "APS ASC Centre & College, Bengaluru" },
  { id: "aps-babina", name: "APS Babina" },
  { id: "aps-bagrakote", name: "APS Bagrakote" },
  { id: "aps-barrackpore", name: "APS Barrackpore" },
  { id: "aps-basistha", name: "APS Basistha" },
  { id: "aps-bathinda", name: "APS Bathinda" },
  { id: "aps-beas", name: "APS Beas" },
  { id: "aps-belagavi", name: "APS Belagavi" },
  { id: "aps-bengaluru", name: "APS Bengaluru" },
  { id: "aps-bengdubi", name: "APS Bengdubi" },
  { id: "aps-bhuj", name: "APS Bhuj" },
  { id: "aps-bhopal", name: "APS Bhopal" },
  { id: "aps-bikaner", name: "APS Bikaner" },
  { id: "aps-binnaguri", name: "APS Binnaguri" },
  { id: "aps-birpur", name: "APS Birpur" },
  { id: "aps-bd-bari", name: "APS BD Bari" },
  { id: "aps-chandimandir", name: "APS Chandimandir" },
  { id: "aps-chennai", name: "APS Chennai" },
  { id: "aps-clement-town", name: "APS Clement Town" },
  { id: "aps-dagshai", name: "APS Dagshai" },
  { id: "aps-dalhousie", name: "APS Dalhousie" },
  { id: "aps-danapur", name: "APS Danapur" },
  { id: "aps-darjeeling", name: "APS Darjeeling" },
  { id: "aps-dehu-road", name: "APS Dehu Road" },
  { id: "aps-devlali", name: "APS Devlali" },
  { id: "aps-dgha-dighi", name: "APS Dgha (Dighi)" },
  { id: "aps-dhar-road", name: "APS Dhar Road" },
  { id: "aps-dharamshala", name: "APS Dharamshala" },
  { id: "aps-dharangadhra", name: "APS Dharangadhra" },
  { id: "aps-dinjan", name: "APS Dinjan" },
  { id: "aps-ferozepur", name: "APS Ferozepur" },
  { id: "aps-fatehgarh", name: "APS Fatehgarh" },
  { id: "aps-gangtok", name: "APS Gangtok" },
  { id: "aps-gaya", name: "APS Gaya" },
  { id: "aps-golconda", name: "APS Golconda" },
  { id: "aps-gwalior", name: "APS Gwalior" },
  { id: "aps-happy-valley", name: "APS Happy Valley" },
  { id: "aps-hempur", name: "APS Hempur" },
  { id: "aps-hisar", name: "APS Hisar" },
  { id: "aps-jaipur", name: "APS Jaipur" },
  { id: "aps-jaisalmer", name: "APS Jaisalmer" },
  { id: "aps-jalandhar-cantt", name: "APS Jalandhar Cantt" },
  { id: "aps-jammu-cantt", name: "APS Jammu Cantt" },
  { id: "aps-jodhpur", name: "APS Jodhpur" },
  { id: "aps-jorhat", name: "APS Jorhat" },
  { id: "aps-jhansi", name: "APS Jhansi" },
  { id: "aps-jabalpur-no-1", name: "APS Jabalpur No. 1" },
  { id: "aps-jabalpur-no-2", name: "APS Jabalpur No. 2" },
  { id: "aps-kalimpong", name: "APS Kalimpong" },
  { id: "aps-kaluchak", name: "APS Kaluchak" },
  { id: "aps-kamptee", name: "APS Kamptee" },
  { id: "aps-kanpur", name: "APS Kanpur" },
  { id: "aps-kannur", name: "APS Kannur" },
  { id: "aps-kapurthala", name: "APS Kapurthala" },
  { id: "aps-khadakwasla", name: "APS Khadakwasla" },
  { id: "aps-kirkee", name: "APS Kirkee" },
  { id: "aps-kolkata", name: "APS Kolkata" },
  { id: "aps-kota", name: "APS Kota" },
  { id: "aps-leh", name: "APS Leh" },
  { id: "aps-lucknow", name: "APS Lucknow" },
  { id: "aps-mamun", name: "APS Mamun" },
  { id: "aps-mathura", name: "APS Mathura" },
  { id: "aps-meerut", name: "APS Meerut" },
  { id: "aps-mic-s-ahmednagar", name: "APS MIC & S Ahmednagar" },
  { id: "aps-miran-sahib", name: "APS Miran Sahib" },
  { id: "aps-missamari", name: "APS Missamari" },
  { id: "aps-mhow", name: "APS Mhow" },
  { id: "aps-mumbai", name: "APS Mumbai" },
  { id: "aps-nagrota", name: "APS Nagrota" },
  { id: "aps-namkum", name: "APS Namkum" },
  { id: "aps-nahan", name: "APS Nahan" },
  { id: "aps-narangi", name: "APS Narangi" },
  { id: "aps-nasirabad", name: "APS Nasirabad" },
  { id: "aps-nehru-road-lucknow", name: "APS Nehru Road, Lucknow" },
  { id: "aps-noida", name: "APS Noida" },
  { id: "aps-pachmarhi", name: "APS Pachmarhi" },
  { id: "aps-panagarh", name: "APS Panagarh" },
  { id: "aps-pathankot", name: "APS Pathankot" },
  { id: "aps-patiala", name: "APS Patiala" },
  { id: "aps-pithoragarh", name: "APS Pithoragarh" },
  { id: "aps-poonch", name: "APS Poonch" },
  { id: "aps-prayagraj", name: "APS Prayagraj" },
  { id: "aps-prtc-bengaluru", name: "APS PRTC, Bengaluru" },
  { id: "aps-pune", name: "APS Pune" },
  { id: "aps-raiwala", name: "APS Raiwala" },
  { id: "aps-rajouri", name: "APS Rajouri" },
  { id: "aps-rakhmuthi", name: "APS Rakhmuthi" },
  { id: "aps-ramgarh", name: "APS Ramgarh" },
  { id: "aps-ranchi", name: "APS Ranchi" },
  { id: "aps-rangapahar", name: "APS Rangapahar" },
  { id: "aps-ranikhet", name: "APS Ranikhet" },
  { id: "aps-ratnuchak", name: "APS Ratnuchak" },
  { id: "aps-rohtak", name: "APS Rohtak" },
  { id: "aps-roorkee", name: "APS Roorkee" },
  { id: "aps-saugor", name: "APS Saugor" },
  { id: "aps-samba", name: "APS Samba" },
  { id: "aps-sangrur", name: "APS Sangrur" },
  { id: "aps-secunderabad", name: "APS Secunderabad" },
  { id: "aps-shillong", name: "APS Shillong" },
  { id: "aps-shrinagar", name: "APS Shrinagar" },
  { id: "aps-sukna", name: "APS Sukna" },
  { id: "aps-sunjuwan", name: "APS Sunjuwan" },
  { id: "aps-suratgarh", name: "APS Suratgarh" },
  { id: "aps-talbehat", name: "APS Talbehat" },
  { id: "aps-tenga-valley", name: "APS Tenga Valley" },
  { id: "aps-tezpur", name: "APS Tezpur" },
  { id: "aps-thiruvananthapuram", name: "APS Thiruvananthapuram" },
  { id: "aps-udaipur", name: "APS Udaipur" },
  { id: "aps-udhampur", name: "APS Udhampur" },
  { id: "aps-umroi", name: "APS Umroi" },
  { id: "aps-uri", name: "APS Uri" },
  { id: "aps-wellington", name: "APS Wellington" },
  { id: "aps-yol", name: "APS Yol" },
  { id: "aps-bareilly", name: "APS Bareilly" },
  { id: "aps-bolarum", name: "APS Bolarum" },
  { id: "aps-damana", name: "APS Damana" },
  { id: "aps-deolali-camp", name: "APS Deolali Camp" },
  { id: "aps-jhakri", name: "APS Jhakri" },
  { id: "aps-ranikhet-cantonment", name: "APS Ranikhet Cantonment" },
  { id: "aps-srinagar", name: "APS Srinagar" },
  { id: "aps-tezu", name: "APS Tezu" },
  { id: "aps-yol-cantt", name: "APS Yol Cantt" },
  { id: "aps-binaguri", name: "APS Binaguri" },
];
